pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  buildProjects: '**/CoronaDashboard.csproj'
  tag: '1.0.0'
  buildNumber: $(Build.BuildNumber)

stages:
- stage: publish_and_deploy
  jobs: 
  - job: publish_and_deploy
    displayName: 'Publish and Deploy with Pulumi'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: publish
        projects: |
         $(buildProjects)
        publishWebProjects: false
        arguments: '--configuration $(BuildConfiguration) /p:Version=1.0.0-$(BuildNumber) --output docs-temp'
        zipAfterPublish: false
        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#file-structure-for-output-files-is-different-from-previous-builds
        modifyOutputPath: false

    - task: pulumi.build-and-release-task.custom-build-release-task.Pulumi@1
      displayName: 'Run pulumi - preview'
      inputs:
        azureSubscription: 'Service Connection for Static Websites'
        command: preview
        cwd: "src/Pulumi"
        stack: "StefH/blazor-corona-dashboard/dev"
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)

    - task: pulumi.build-and-release-task.custom-build-release-task.Pulumi@1
      displayName: 'Run pulumi - up'
      condition: and(succeeded(), eq(variables['PULUMI_UP'], 'yes'))
      inputs:
        azureSubscription: 'Service Connection for Static Websites'
        command: up
        cwd: "src/Pulumi"
        args: "--yes"
        stack: "StefH/blazor-corona-dashboard/dev"
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)