//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaDashboard.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoronaDashboard.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont de leeftijdsverdeling per vijf-jaars categorie van IC-patiënten met verdachte of bewezen COVID-19 naar uitkomst..
        /// </summary>
        internal static string AgeDistribution_BodyText {
            get {
                return ResourceManager.GetString("AgeDistribution_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijdsdistributie van IC-patiënten met verdachte of bewezen COVID-19 naar uitkomst..
        /// </summary>
        internal static string AgeDistribution_Header {
            get {
                return ResourceManager.GetString("AgeDistribution_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijdsverdeling.
        /// </summary>
        internal static string AgeDistribution_X {
            get {
                return ResourceManager.GetString("AgeDistribution_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal IC opnamen.
        /// </summary>
        internal static string AgeDistribution_Y {
            get {
                return ResourceManager.GetString("AgeDistribution_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont de verdeling van de IC-behandelduur van patiënten die met verdachte of bewezen COVID-19 status op de IC opgenomen zijn of zijn geweest. De behandelduur wordt afgekapt op 60 dagen. Deze grafiek is zeer dynamisch..
        /// </summary>
        internal static string BehandelduurDistribution_BodyText {
            get {
                return ResourceManager.GetString("BehandelduurDistribution_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributie van de IC-behandelduur van patiënten met verdachte of bewezen COVID-19 naar uitkomst.
        /// </summary>
        internal static string BehandelduurDistribution_Header {
            get {
                return ResourceManager.GetString("BehandelduurDistribution_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behandelduur (in dagen).
        /// </summary>
        internal static string BehandelduurDistribution_X {
            get {
                return ResourceManager.GetString("BehandelduurDistribution_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal IC opnamen.
        /// </summary>
        internal static string BehandelduurDistribution_Y {
            get {
                return ResourceManager.GetString("BehandelduurDistribution_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Stef Heyenrath 2020 - 2022 (&lt;a href=&quot;https://github.com/StefH/CoronaDashboard&quot;&gt;source&lt;/a&gt;).
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont per dag het cumulatief aantal IC-patiënten met verdachte en bewezen COVID-19 status. Dit cijfer is een gemiddelde van de afgelopen {0} dagen..
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_BodyText {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het cumulatief aantal patiënten met verdachte of bewezen COVID-19 per dag..
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_Header {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overleden bij IC opname: {0}.
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_Overleden {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_Overleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het ziekenhuis levend verlaten: {0}.
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_Verlaten {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_Verlaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog opgenomen op de verpleegafdeling: {0}.
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_Verpleegafdeling {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_Verpleegafdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont het aantal testen en positieve testen per dag via GGD teststraten. Het cijfer in de grafiek is een gemiddelde van de afgelopen {0} dagen..
        /// </summary>
        internal static string GGDGetestePersonenPerDag_BodyText1 {
            get {
                return ResourceManager.GetString("GGDGetestePersonenPerDag_BodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal positieve en aantal geteste personen voor COVID-19.
        /// </summary>
        internal static string GGDGetestePersonenPerDag_Header {
            get {
                return ResourceManager.GetString("GGDGetestePersonenPerDag_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getest {0}: {1}.
        /// </summary>
        internal static string GGDGetestePersonenPerDag_TodayAndTotal {
            get {
                return ResourceManager.GetString("GGDGetestePersonenPerDag_TodayAndTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string GGDGetestePersonenPerDag_X {
            get {
                return ResourceManager.GetString("GGDGetestePersonenPerDag_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale testen.
        /// </summary>
        internal static string GGDGetestePersonenPerDag_Y {
            get {
                return ResourceManager.GetString("GGDGetestePersonenPerDag_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positief {0}: {1}.
        /// </summary>
        internal static string GGDPositiefGetestePersonenPerDag_TodayAndTotal {
            get {
                return ResourceManager.GetString("GGDPositiefGetestePersonenPerDag_TodayAndTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positieve testen.
        /// </summary>
        internal static string GGDPositiefGetestePersonenPerDag_Y {
            get {
                return ResourceManager.GetString("GGDPositiefGetestePersonenPerDag_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont hoeveel patiënten met verdachte of bewezen COVID-19 status per dag op de IC’s aanwezig waren. Het gaat hierbij dus om de reeds aanwezige COVID-19 patiënten en de nieuwe opgenomen COVID-19 patiënten per dag. Dit cijfer is een gemiddelde van de afgelopen {0} dagen..
        /// </summary>
        internal static string IntakeCount_BodyText {
            get {
                return ResourceManager.GetString("IntakeCount_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het totaal aantal aanwezige patiënten met verdachte of bewezen COVID-19 op de IC per dag..
        /// </summary>
        internal static string IntakeCount_Header {
            get {
                return ResourceManager.GetString("IntakeCount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal IC patiënten {0}: {1}.
        /// </summary>
        internal static string IntakeCount_Today {
            get {
                return ResourceManager.GetString("IntakeCount_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string IntakeCount_X {
            get {
                return ResourceManager.GetString("IntakeCount_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal IC opnamen.
        /// </summary>
        internal static string IntakeCount_Y {
            get {
                return ResourceManager.GetString("IntakeCount_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het ziekenhuis levend verlaten.
        /// </summary>
        internal static string Label_Gezond {
            get {
                return ResourceManager.GetString("Label_Gezond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog opgenomen op de IC.
        /// </summary>
        internal static string Label_IC {
            get {
                return ResourceManager.GetString("Label_IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overleden bij IC opname.
        /// </summary>
        internal static string Label_Overleden {
            get {
                return ResourceManager.GetString("Label_Overleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog opgenomen op de verpleegafdeling.
        /// </summary>
        internal static string Label_Verpleegafdeling {
            get {
                return ResourceManager.GetString("Label_Verpleegafdeling", resourceCulture);
            }
        }
    }
}
