//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaDashboard.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoronaDashboard.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont de leeftijdsverdeling per vijf-jaars categorie van IC-patiënten met verdachte of bewezen COVID-19 naar uitkomst..
        /// </summary>
        internal static string AgeDistribution_BodyText {
            get {
                return ResourceManager.GetString("AgeDistribution_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijdsdistributie van IC-patiënten met verdachte of bewezen COVID-19 naar uitkomst..
        /// </summary>
        internal static string AgeDistribution_Header {
            get {
                return ResourceManager.GetString("AgeDistribution_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijdsverdeling.
        /// </summary>
        internal static string AgeDistribution_X {
            get {
                return ResourceManager.GetString("AgeDistribution_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal IC opnamen.
        /// </summary>
        internal static string AgeDistribution_Y {
            get {
                return ResourceManager.GetString("AgeDistribution_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont per dag het cumulatief aantal IC-patiënten met verdachte en bewezen COVID-19 status. Dit cijfer is een gemiddelde van de afgelopen drie dagen..
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_BodyText {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het cumulatief aantal patiënten met verdachte of bewezen COVID-19 per dag..
        /// </summary>
        internal static string DiedAndSurvivorsCumulative_Header {
            get {
                return ResourceManager.GetString("DiedAndSurvivorsCumulative_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze grafiek toont hoeveel patiënten met verdachte of bewezen COVID-19 status per dag op de IC’s aanwezig waren. Het gaat hierbij dus om de reeds aanwezige COVID-19 patiënten en de nieuwe opgenomen COVID-19 patiënten per dag. Dit cijfer is een gemiddelde van de afgelopen drie dagen..
        /// </summary>
        internal static string IntakeCount_BodyText {
            get {
                return ResourceManager.GetString("IntakeCount_BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het totaal aantal aanwezige patiënten met verdachte of bewezen COVID-19 op de IC per dag..
        /// </summary>
        internal static string IntakeCount_Header {
            get {
                return ResourceManager.GetString("IntakeCount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string IntakeCount_X {
            get {
                return ResourceManager.GetString("IntakeCount_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal IC opnamen.
        /// </summary>
        internal static string IntakeCount_Y {
            get {
                return ResourceManager.GetString("IntakeCount_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het ziekenhuis levend verlaten.
        /// </summary>
        internal static string Label_Gezond {
            get {
                return ResourceManager.GetString("Label_Gezond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog opgenomen op de IC.
        /// </summary>
        internal static string Label_IC {
            get {
                return ResourceManager.GetString("Label_IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overleden bij IC opname.
        /// </summary>
        internal static string Label_Overleden {
            get {
                return ResourceManager.GetString("Label_Overleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog opgenomen op de verpleegafdeling.
        /// </summary>
        internal static string Label_Verpleegafdeling {
            get {
                return ResourceManager.GetString("Label_Verpleegafdeling", resourceCulture);
            }
        }
    }
}
